### ISSUE TITLE
Contents in a duplicate tab have not been highlighted.

### ISSUE THREAD

**Issue by howardhhm** [fabiospampinato/vscode-highlight#12]
As shown in the title.

**Comment by fabiospampinato** [comment]
It looks like a bug to me, thanks for reporting it!

**Comment by fabiospampinato** [comment]
Fixed in v1.2.4.

**Comment by howardhhm** [comment]
It seems that this bug still exists if you add a new blank line. However after switching tabs, the code will be highlighted again. Maybe it is software confliction in my VS Code?

**Comment by fabiospampinato** [comment]
@howardhhm I can't reproduce that, can you make me a GIF or something?

**Comment by howardhhm** [comment]
Press `cmd`+`\` to split editor.
![bug](https://user-images.githubusercontent.com/5356133/43623273-f3c9d880-9712-11e8-9511-d289bea32087.gif)

**Comment by fabiospampinato** [comment]
I still can't reproduce it. Can you share with me the content of the file, and all your settings (or at least anything possibly related with the issue)?

**Comment by howardhhm** [comment]
1. I download the latest VS Code.
2. User Settings(No additional settings):
```
{
    "highlight.regexes": {
        "(\\[ERROR])([^(\\\\|\\()]*)": [
            {
                "overviewRulerColor": "#ff932d",
                "backgroundColor": "#ff932d",
                "color": "#1f1f1f",
                "fontWeight": "bold"
            },
            {
                "backgroundColor": "#d9ad00",
                "color": "#1f1f1f"
            }
        ]
    }
}
```
3. Type the following code:
language:php
```php
<?php
echo '[ERROR] Message';
```
3. And press `CMD`+`\` to split editor.
4. In the split tab, press `Enter`.
5. And the bug reveals.
6. Switch the tabs, the content is highlighted again.

![image](https://user-images.githubusercontent.com/5356133/43644346-ffb37324-9760-11e8-9020-5fe8d6cf7760.png)

**Comment by fabiospampinato** [comment]
@howardhhm now I can reproduce it 👍 Let's see what the problem is...

**Comment by fabiospampinato** [comment]
Should be fixed now, thank again!

**Comment by howardhhm** [comment]
Great! Thank you for your timely fix.
I love this extention so much that I can hightlight the comments I want.
